// src/components/Greeting.jsx
import React, { useState, useEffect } from "react";

function Greeting() {
  const [greetingText, setGreetingText] = useState("");
  useEffect(() => {
    const currentTime = new Date();
    const currentHours = currentTime.getHours();
    if (currentHours < 12) {
      setGreetingText("Buenos días");
    } else if (currentHours < 18) {
      setGreetingText("Buenas tardes");
    } else {
      setGreetingText("Buenas noches");
    }
  }, []);

  return <h1 className="text-4xl pt-6">{greetingText}</h1>;


}

export default Greeting;

// src/components/Greeting.svelte
<script lang="ts">
  const currentTime = new Date();
  const currentHour = currentTime.getHours();
  let greeting = "";

  if (currentHour < 12) {
    greeting = "Buenos días";
  } else if (currentHour < 18) {
    greeting = "Buenas tardes";
  } else {
    greeting = "Buenas noches";
  }
</script>

<h1 class="text-4xl pt-6">{greeting}</h1>
